# This is used with the label workflow which
# will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# For more information, see:
# https://github.com/actions/labeler

Utility:
- changed-files:
  - any-glob-to-any-file: utils/*

Component:
- changed-files:
  - any-glob-to-any-file: components/*

Github: 
- changed-files: 
  - any-glob-to-any-file: '.github/*'

feature:
  - head-branch: '^feature'

fix:
  - head-branch: '^fix'

refactor:
  - head-branch: '^refactor'

devFeature:
  - head-branch: '^devFeature'

devFix:
  - head-branch: '^devFix'

release:
  - base-branch: main

# 'package: core':
# - changed-files:
#   - any-glob-to-any-file: ['core/**/*']

# 'package: angular':
# - changed-files:
#   - any-glob-to-any-file: ['packages/angular/**/*', 'packages/angular-*/**/*']

# 'package: react':
# - changed-files:
#   - any-glob-to-any-file: ['packages/react/**/*', 'packages/react-*/**/*']

# 'package: vue':
# - changed-files:
#   - any-glob-to-any-file: ['packages/vue/**/*', 'packages/vue-*/**/*']